name: basic-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello from GitHub Actions"

      - name: Show user
        run: echo "User is ${{ github.actor }}"

      - name: Show workflow
        run: echo "Workflow is ${{ github.workflow }}"
