name: unit-test

on:
workflow_dispatch:
inputs:
text:
description: 'Enter what you want to print'
default: 'Hello'
required: true
type: string

env:
firstName: "Autmn"
webSite: "testing mini bites"

jobs:
context-demo:
timeout-minutes: 10
continue-on-error: false

container:
image: selenium/standalone-chrome:latest

runs-on: ubuntu-latest

steps:
- run: echo "${{ inputs.text }}"
- run: echo "${{ github.event.inputs.text }}"
- run: echo "${{ github.actor }}"
- run: echo "Hi ${{ env.firstName }} ${{ env.webSite }}"
- run: echo "${{ github.workflow }}"
- run: echo "${{ github.event_name }}"

- name: Print secret
run: echo "${{ secrets.PASSWORD }} ${{ env.firstName }}"
env:
firstName: "Autmn"

context-demo2:
needs: context-demo
runs-on: ubuntu-latest

steps:
- run: echo "context-demo2 running after context-demo"

job3:
if: ${{ always() }}
needs: context-demo
runs-on: ubuntu-latest

steps:
- run: echo "job3 running after context-demo"

job4:
if: ${{ failure() }}
needs: context-demo
runs-on: ubuntu-latest

steps:
- run: echo "job4 running after context-demo"
