name: basic-test

on:
  workflow_dispatch:
    inputs:
      text:
        description: "What do you want to print?"
        required: true
        default: "Hello"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ inputs.text }}"

      - name: Print GitHub user
        run: echo "Running by ${{ github.actor }}"

      - name: Print workflow
        run: echo "Workflow: ${{ github.workflow }}"
